### Generate token ###
GET http://localhost:8080/jwt/hs256/token

### Decode token ###
GET http://localhost:8080/jwt/hs256/decode
Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtc2ciOiJUaGlzIGlzIHRlc3QgdG9rZW4uIiwic3ViIjoidXNlciIsImlzcyI6InBsYWluYmxvY2siLCJhZG0iOmZhbHNlLCJleHAiOjE2NjE0NDExODAsImlhdCI6MTY2MTQzNzU4MH0.3gG8RvMKZVeBgSKPO44mdzBuD_3vU32U_nEllD3uCh8

### Verify token ###
GET http://localhost:8080/jwt/hs256/verify
Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtc2ciOiJUaGlzIGlzIHRlc3QgdG9rZW4uIiwic3ViIjoidXNlciIsImlzcyI6InBsYWluYmxvY2siLCJhZG0iOmZhbHNlLCJleHAiOjE2NjE0NDExODAsImlhdCI6MTY2MTQzNzU4MH0.3gG8RvMKZVeBgSKPO44mdzBuD_3vU32U_nEllD3uCh8

### Check flag ###
GET http://localhost:8080/jwt/hs256/flag
Flag: flag